# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the contents of the repository to the working directory
COPY . .

# Install the project dependencies
RUN pip install uv
RUN uv sync

# Expose the port that the server will run on
EXPOSE 8000

# Command to run the server
CMD ["uv", "run", "src", "--transport", "http"]
